### ISSUE TITLE
RuntimeError: value cannot be converted to type int without overflow

### ISSUE THREAD

**Issue by xuxiaoang** [whyNLP/PCCoT#1]
Nice work!

When I run `run_cot.sh` and `run_ccot.sh` with a single GPU, both are normal.

However, when using multiple GPUs, the training gets stuck at the first epoch, then the following error occurs:

```
[rank0]:[W806 22:27:47.125539394 reducer.cpp:1400] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
[WARNING|logging.py:328] 2025-08-06 22:27:47,781 >> DynamicCache + torch.export is tested on torch 2.6.0+ and may not work on earlier versions.
[rank1]:[E806 22:57:48.409857537 ProcessGroupNCCL.cpp:616] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=157, OpType=ALLGATHER, NumelIn=1, NumelOut=2, Timeout(ms)=1800000) ran for 1800050 milliseconds before timing out.
[rank1]:[E806 22:57:48.410108787 ProcessGroupNCCL.cpp:1785] [PG ID 0 PG GUID 0(default_pg) Rank 1] Exception (either an error or timeout) detected by watchdog at work: 157, last enqueued NCCL work: 157, last completed NCCL work: 156.
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/xuxiaoang/LatentCoT/PCCoT/run_ccot.py", line 826, in <module>
[rank1]:     main()
[rank1]:   File "/home/xuxiaoang/LatentCoT/PCCoT/run_ccot.py", line 754, in main
[rank1]:     train_result = trainer.train(resume_from_checkpoint=checkpoint)
[rank1]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/xuxiaoang/anaconda3/envs/Latent/lib/python3.12/site-packages/transformers/trainer.py", line 2206, in train
[rank1]:     return inner_training_loop(
[rank1]:            ^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/xuxiaoang/anaconda3/envs/Latent/lib/python3.12/site-packages/accelerate/utils/memory.py", line 174, in decorator
[rank1]:     return function(batch_size, *args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/xuxiaoang/anaconda3/envs/Latent/lib/python3.12/site-packages/transformers/trainer.py", line 2362, in _inner_training_loop
[rank1]:     model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
[rank1]:                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/xuxiaoang/anaconda3/envs/Latent/lib/python3.12/site-packages/accelerate/accelerator.py", line 1453, in prepare
[rank1]:     result = tuple(
[rank1]:              ^^^^^^
[rank1]:   File "/home/xuxiaoang/anaconda3/envs/Latent/lib/python3.12/site-packages/accelerate/accelerator.py", line 1454, in <genexpr>
[rank1]:     self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
[rank1]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/xuxiaoang/anaconda3/envs/Latent/lib/python3.12/site-packages/accelerate/accelerator.py", line 1302, in _prepare_one
[rank1]:     return self.prepare_model(obj, device_placement=device_placement)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/xuxiaoang/anaconda3/envs/Latent/lib/python3.12/site-packages/accelerate/accelerator.py", line 1669, in prepare_model
[rank1]:     model = torch.nn.parallel.DistributedDataParallel(
[rank1]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/xuxiaoang/anaconda3/envs/Latent/lib/python3.12/site-packages/torch/nn/parallel/distributed.py", line 825, in __init__
[rank1]:     _verify_param_shape_across_processes(self.process_group, parameters)
[rank1]:   File "/home/xuxiaoang/anaconda3/envs/Latent/lib/python3.12/site-packages/torch/distributed/utils.py", line 288, in _verify_param_shape_across_processes
[rank1]:     return dist._verify_params_across_processes(process_group, tensors, logger)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]: RuntimeError: value cannot be converted to type int without overflow
[rank0]:[E806 22:57:48.550386573 ProcessGroupNCCL.cpp:616] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=157, OpType=ALLREDUCE, NumelIn=1310720, NumelOut=1310720, Timeout(ms)=1800000) ran for 1800063 milliseconds before timing out.
[rank0]:[E806 22:57:48.550613673 ProcessGroupNCCL.cpp:1785] [PG ID 0 PG GUID 0(default_pg) Rank 0] Exception (either an error or timeout) detected by watchdog at work: 157, last enqueued NCCL work: 172, last completed NCCL work: 156.
[rank1]:[E806 22:57:48.027738771 ProcessGroupNCCL.cpp:1834] [PG ID 0 PG GUID 0(default_pg) Rank 1] Timeout at NCCL work: 157, last enqueued NCCL work: 157, last completed NCCL work: 156.
[rank1]:[E806 22:57:48.027771463 ProcessGroupNCCL.cpp:630] [Rank 1] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank1]:[E806 22:57:48.027776129 ProcessGroupNCCL.cpp:636] [Rank 1] To avoid data inconsistency, we are taking the entire process down.
[rank1]:[E806 22:57:48.028936038 ProcessGroupNCCL.cpp:1595] [PG ID 0 PG GUID 0(default_pg) Rank 1] Process group watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=157, OpType=ALLGATHER, NumelIn=1, NumelOut=2, Timeout(ms)=1800000) ran for 1800050 milliseconds before timing out.
Exception raised from checkTimeout at /opt/conda/conda-bld/pytorch_1729647406761/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:618 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7faf8c8fc446 in /home/xuxiaoang/anaconda3/envs/Latent/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x282 (0x7faf8dbb77f2 in /home/xuxiaoang/anaconda3/envs/Latent/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::watchdogHandler() + 0x233 (0x7faf8dbbec33 in /home/xuxiaoang/anaconda3/envs/Latent/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7faf8dbc069d in /home/xuxiaoang/anaconda3/envs/Latent/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0x145c0 (0x7fafdf1d25c0 in /home/xuxiaoang/anaconda3/envs/Latent/lib/python3.12/site-packages/torch/lib/libtorch.so)
frame #5: <unknown function> + 0x94ac3 (0x7fafff5e9ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #6: <unknown function> + 0x126850 (0x7fafff67b850 in /lib/x86_64-linux-gnu/libc.so.6)

W0806 22:57:48.943000 2072184 site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2072278 closing signal SIGTERM
E0806 22:57:49.158000 2072184 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: -6) local_rank: 1 (pid: 2072279) of binary: /home/xuxiaoang/anaconda3/envs/Latent/bin/python3.12
Traceback (most recent call last):
  File "/home/xuxiaoang/anaconda3/envs/Latent/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/xuxiaoang/anaconda3/envs/Latent/lib/python3.12/site-packages/accelerate/commands/accelerate_cli.py", line 50, in main
    args.func(args)
  File "/home/xuxiaoang/anaconda3/envs/Latent/lib/python3.12/site-packages/accelerate/commands/launch.py", line 1190, in launch_command
    multi_gpu_launcher(args)
  File "/home/xuxiaoang/anaconda3/envs/Latent/lib/python3.12/site-packages/accelerate/commands/launch.py", line 815, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/xuxiaoang/anaconda3/envs/Latent/lib/python3.12/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/xuxiaoang/anaconda3/envs/Latent/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xuxiaoang/anaconda3/envs/Latent/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
========================================================
run_ccot.py FAILED
--------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
--------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-08-06_22:57:48
  host      : localhost
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 2072279)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 2072279
========================================================

```

This seems to be an error caused by NCCL timeout.

How can I solve it?

**Comment by why-in-Shanghaitech** [comment]
Hi, thank you for reaching out!

I haven't seen this error before. I guess it is just due to an incompatibility with the packages (https://github.com/shibing624/MedicalGPT/issues/222). Below is the result of `pip freeze` from my environment, see if this helps:

```
accelerate==1.6.0
aiohappyeyeballs==2.6.1
aiohttp==3.11.18
aiosignal==1.3.2
annotated-types==0.7.0
attrs==25.3.0
certifi==2025.4.26
charset-normalizer==3.4.2
click==8.1.8
datasets==3.5.1
dill==0.3.8
docker-pycreds==0.4.0
einops==0.8.1
emoji==2.14.1
evaluate==0.4.3
Faker==37.1.0
filelock @ file:///croot/filelock_1744281381737/work
flash_attn @ https://github.com/Dao-AILab/flash-attention/releases/download/v2.7.4.post1/flash_attn-2.7.4.post1+cu12torch2.5cxx11abiFALSE-cp312-cp312-linux_x86_64.whl#sha256=a496f383c843ed0cc6e01302556a0947f56828f1ec2b54e5297c4c7eaae39357
frozenlist==1.6.0
fsspec==2025.3.0
gitdb==4.0.12
GitPython==3.1.44
gmpy2 @ file:///croot/gmpy2_1738085463648/work
huggingface-hub==0.30.2
idna==3.10
Jinja2 @ file:///croot/jinja2_1741710844255/work
joblib==1.5.0
liger_kernel==0.5.9
markdown-it-py==3.0.0
MarkupSafe @ file:///croot/markupsafe_1738584038848/work
mdurl==0.1.2
mpmath @ file:///work/perseverance-python-buildout/croot/mpmath_1698864994882/work
multidict==6.4.3
multiprocess==0.70.16
networkx @ file:///croot/networkx_1737039604450/work
npyscreen==4.10.5
numpy==2.2.5
packaging==25.0
pandas==2.2.3
peft==0.15.2
pexpect==4.9.0
platformdirs==4.3.7
propcache==0.3.1
protobuf==6.30.2
psutil==7.0.0
ptyprocess==0.7.0
pyarrow==20.0.0
pydantic==2.11.4
pydantic_core==2.33.2
Pygments==2.19.1
pyotp==2.9.0
python-dateutil==2.9.0.post0
pytz==2025.2
PyYAML @ file:///croot/pyyaml_1728657952215/work
regex==2024.11.6
requests==2.32.3
rich==14.0.0
ruamel.yaml==0.18.10
ruamel.yaml.clib==0.2.12
safetensors==0.5.3
sapp-py==0.5.0.dev1
scikit-learn==1.6.1
scipy==1.15.2
sentencepiece==0.2.0
sentry-sdk==2.27.0
setproctitle==1.3.6
setuptools==78.1.1
six==1.17.0
slash-py==0.0.1.dev1
smmap==5.0.2
stanza==1.10.1
sympy==1.13.1
threadpoolctl==3.6.0
tokenizers==0.20.3
torch==2.5.1
tqdm==4.67.1
transformers==4.46.3
triton==3.1.0
typing-inspection==0.4.0
typing_extensions @ file:///croot/typing_extensions_1734714854207/work
tzdata==2025.2
urllib3==2.4.0
wandb==0.19.10
wheel==0.45.1
xxhash==3.5.0
yarl==1.20.0
```

Feel free to add a follow-up if you need any further assistance.

**Comment by xuxiaoang** [comment]
Thanks! It solves the error.
